import './intersection-observer.js';
import './accordion.js';
import './navigation.js';

// Removes all empty p tags generated by wordpress
( function($) {
	$( 'p:empty' ).remove();

	$( 'p' ).each( function() {
		if ( $( this ).text().trim().length == 0 ) {
			$( this ).remove()
		}
	});
}(jQuery) );